### ISSUE TITLE
Create Schema

### ISSUE THREAD

**Issue by chelseaworrel** [chelseaworrel/traffic-spy-skeleton#1]

**Comment by RickBacci** [comment]
Do i have to do anything special with waffle.io?

**Comment by RickBacci** [comment]
i see it now

**Comment by rickbacci** [comment]
Here's what I have so far. I have the .xml saved locally.

https://www.dropbox.com/s/9jcma6eni9tesrt/Screenshot%202015-05-27%2000.23.09.png?dl=0

User registers here
http://yourapplication:port/sources

with:
params[:identifier]
params[:rootUrl]

A registered application will send POST requests to the following URL:
http://yourapplication:port/sources/IDENTIFIER/data

Where IDENTIFIER is the unique identifier generated previously for this site. The request will contain a parameter named ‘payload’ which contains JSON data with this structure:

payload = { 
"url":"http://jumpstartlab.com/blog”, 
"requestedAt":"2013-02-16 21:38:28 -0700”, 
"respondedIn":37, 
"referredBy":"http://jumpstartlab.com”, 
"requestType":"GET”, 
"parameters":[], 
"eventName": "socialLogin”, 
"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1309.0 Safari/537.17”, 
"resolutionWidth":"1920”, 
"resolutionHeight":"1280”, 
"ip":"63.29.38.211” 
}

We need to store the following:
- identifier
- rootUrl 
- url
- requestedAt
- respondedIn
- referredBy
- requestType
- parameters
- eventName
- userAgent
- resolutionWidth
- resolutionHeight
- ip

## Application Details
- Most requested URLS to least requested URLS (url)
- Web browser breakdown across all requests (userAgent)
- OS breakdown across all requests (userAgent)
- Screen Resolution across all requests (resolutionWidth x resolutionHeight)
- Longest, average response time per URL to shortest, average response time per URL
- Hyperlinks of each url to view url specific data
- Hyperlink to view aggregate event data

## Application URL Statistics
- Longest response time
- Shortest response time
- Average response time
- Which HTTP verbs have been used
- Most popular referrrers
- Most popular user agents

## Relationship possibilities
- users have_many sites
- sites belong_to users
- sites have_many pages
- pages belong_to sites
- pages have_many visitors
- pages have_many requests
- pages have_many referrers
- requests have_many response_times
- requests have_many screen_resolutions
- requests have many user_agents
