### ISSUE TITLE
Source registers successfully

### ISSUE THREAD

**Issue by chelseaworrel** [chelseaworrel/traffic-spy-skeleton#5]
As a user:
When I send a POST request to 
http://yourapplication:port/sources
with the paramaters: 
'identifier=jumpstartlab and rootUrl=http://jumpstartlab.com'
Then I expect a 200 response with the data as JSON {"identifier":"jumpstartlab"}

As a user:
When I send a POST request to 
http://yourapplication:port/sources
with the paramaters: 
'rootUrl=http://jumpstartlab.com'
Then I expect a 400 response with a descriptive error message

ML: a 400 response is returned if there are any missing parameters. We should test for "missing 'identifier'" and "missing 'identifier' and 'rootURL'  too".

**Comment by rickbacci** [comment]
As a user:
When I send a POST request to 
http://yourapplication:port/sources
with the paramaters: 
'identifier=jumpstartlab and rootUrl=http://jumpstartlab.com'
Then I expect a 403 response with "Identifier already exists" if the source already exists.

**Comment by ghost** [comment]
we should make sure that we have validations in the models
http://guides.rubyonrails.org/active_record_validations.html
