### ISSUE TITLE
Schema Design Relationships

### ISSUE THREAD

**Issue by chelseaworrel** [chelseaworrel/traffic-spy-skeleton#8]

**Comment by chelseaworrel** [comment]
Sources:
identifier
root_url
has_many : pages

Pages:
url
source_id
belong_to :sources
has_many : requests

Requests
requested_at
requested_in
request_type
event_name
page_id
user_id
belongs_to :user
belongs_to :page

Users
IP
user_agen
resolution_width
resoltuion_height
has_many :requests

**Comment by rickbacci** [comment]
Great job. I think between what i learned and what you both came up with we are going to be in great shape.
